global:
  scrape_interval: 5s
 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
 
  - job_name: 'vehicle_api'
    static_configs:
      - targets: ['host.docker.internal:8000']
 
  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']

  